create table posts
(
    post_id     int8 generated by default as identity,
    user_id     varchar(255) not null,
    photo_id    varchar(255) not null,
    post_text   varchar(2048) not null,
    post_date   timestamp not null,
    primary key (post_id)
);